### ISSUE TITLE
Problem with running the dryrun-diff step for the first time in a feature branch

### ISSUE THREAD

**Issue by robertstettner** [manheim/manheim-c7n-tools#25]
Hi,

I'm trying to run the `dryrun-diff` step in a feature branch and get the following error:
```
[2020-04-02 11:35:01,646 INFO] Step dryrun-diff in REGION 4 of 4 (us-west-2)
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Traceback (most recent call last):
  File "/usr/local/bin/manheim-c7n-runner", line 11, in <module>
    load_entry_point('manheim-c7n-tools', 'console_scripts', 'manheim-c7n-runner')()
  File "/manheim_c7n_tools/manheim_c7n_tools/runner.py", line 622, in main
    args.ACTION, args.regions, step_names=args.steps, skip_steps=args.skip
  File "/manheim_c7n_tools/manheim_c7n_tools/runner.py", line 484, in run
    self._run_step_in_regions(action, step, regions)
  File "/manheim_c7n_tools/manheim_c7n_tools/runner.py", line 539, in _run_step_in_regions
    step(region_name, region_conf).dryrun()
  File "/manheim_c7n_tools/manheim_c7n_tools/runner.py", line 330, in dryrun
    DryRunDiffer(self.config).run(diff_against='origin/master')
  File "/manheim_c7n_tools/manheim_c7n_tools/dryrun_diff.py", line 51, in run
    changed_policies = self._find_changed_policies(git_dir, diff_against)
  File "/manheim_c7n_tools/manheim_c7n_tools/dryrun_diff.py", line 89, in _find_changed_policies
    cwd=git_dir
  File "/usr/local/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'diff', '--name-only', 'origin/master']' returned non-zero exit status 128.
```

Is there something that I need to check-in for the `master` branch?

**Comment by jantman** [comment]
Hmm... it's _possible_ that the dryrun-diff command doesn't completely work anymore. But aside from that, yes. Do you use a default branch name other than ``master``?

**Comment by robertstettner** [comment]
No I use `master`. But I don't have anything checked into it other than the policies directory and the config file.

**Comment by jantman** [comment]
That should be fine... are you not running manheim-c7n-tools in a clone of that repo, or did you name your remote something other than the default of ``origin``? Do you get the same result if you directly run ``git diff --name-only origin/master``?

**Comment by robertstettner** [comment]
@jantman I figured out that it was my CI tool, Drone, which was cloning the repository by only fetching the branch it was running the job with. Nothing to do with the tool. 😄

**Comment by jantman** [comment]
Ahhh, ok! Good to know though!
